app = "zyon-arcade"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[http_service.tcp_checks]]
    interval = "15s"
    timeout = "2s"
