# fly.toml app configuration file generated for zyonarcade on 2026-05-15T20:37:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zyonarcade"
primary_region = "yyz"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'
  memory_mb = 256
